Asynchronous celery solving issue #49
Baschdl/match4healthcare pull request #120
Opened 2020-03-25 22:26 UTC by kevihiiin

- Added Celery support for asynchronous task scheduling.
- Using django-celery-mail to send mails and mass mails asynchronously.

**Celery is only activated in production**, as it needs to be run in addition to Django and needs a message broker like RabbitMQ.
For testing in development, setup RabbitMQ (e.g. using Docker) and start Celery by running:
```shell_script
celery -A match4healthcare worker -l info
```

With `DJANGO_SETTINGS_MODULE` set to the settings file.
Then change `USE_CELERY` in settings to True

2020-03-25 22:41 UTC, Baschdl requested changes
Did not test it locally yet

2020-03-25 22:41 UTC, Baschdl commented on backend/apps/accounts/views.py
> +def send_password_set_email(email, host, template='registration/password_reset_email_.html'):
Checked with @josauder. Should be `password_set_email_.html`

2020-03-25 22:41 UTC, Baschdl commented on backend/apps/iamstudent/tasks.py
> +from celery import shared_task
What's this?

2020-03-25 22:41 UTC, Baschdl commented on backend/apps/iamstudent/views.py
> +            if not (any(x in m.subject for x in forbidden_chars) and any(x in m.student.user.email for x in forbidden_chars)):
Is this the save way to secure it?

2020-03-25 22:43 UTC, kevihiiin commented on backend/apps/accounts/views.py
> +def send_password_set_email(email, host, template='registration/password_reset_email_.html'):
You are correct, in the old branch the file wasn't moved and I changed it.

2020-03-25 22:44 UTC, kevihiiin commented on backend/apps/iamstudent/tasks.py
> +from celery import shared_task
I wanted to write the whole send-mail from scratch and this is a relict. Whole file can be ignored

2020-03-25 22:49 UTC, kevihiiin commented on backend/apps/iamstudent/views.py
> +            if not (any(x in m.subject for x in forbidden_chars) and any(x in m.student.user.email for x in forbidden_chars)):
According to [some](https://de.wikipedia.org/wiki/Header-Injection) [sources](https://www.acunetix.com/blog/articles/email-header-injection/) this attack is based on adding newlines to headers like subject and sender / recipient field. Checking for line returns should avoid it. Django should also check it and fail if it detects any linebreaks. Relying on just Django is bad, as it would remove all mails that are in the queue which are not send yet.

2020-03-26 14:49 UTC, Baschdl commented
We still have to test this properly

2020-03-27 04:51 UTC, Baschdl approved these changes

2020-04-03 02:20 UTC, Baschdl requested changes
We need a proper way to test this

2020-05-06 20:53 UTC, Baschdl commented
Closed due to inactivity, reopen if new progress is made

2020-05-06 20:53 UTC, closed without merging