Deployment changes
Baschdl/match4healthcare pull request #250
Opened 2020-03-28 06:09 UTC by maltezacharias

Umstellung auf neue Deploymentstruktur
Automatisches Deployment per Webhook

2020-03-28 06:45 UTC, Baschdl requested changes
Please change ./deploy.sh accordingly. I would use a parameter or an environment variable for dev/prod.

2020-03-29 18:33 UTC, Baschdl commented on docker-compose.prod.yml
> +     - ./database/data:/database
What's the idea behind this?

2020-03-29 18:33 UTC, Baschdl commented on mkdeployment-environment.sh
> +[
Could be placed in a separate file with parameters

2020-03-29 18:39 UTC, Baschdl commented
Also concerning build on travis, do we wanna introduce a environment variable `STAGE` set to either `dev` or `prod`? We had another feature where it would be helpful.

2020-05-02 19:14 UTC, closed without merging

2020-05-02 19:17 UTC, maltezacharias commented
As discussed with @Baschdl closing this PR in favour of building and pulling Docker images, new issue will be created

2020-05-02 19:49 UTC, Baschdl reviewed
Salvageable:
- '${BACKEND_PORT:-80}:8000'
- non-root