Add user count REST route
Baschdl/match4healthcare pull request #264
Opened 2020-03-28 13:30 UTC by feeds

First part of #193
Duplicate of #214 (was branched from old staging)

@andyz02 you can call /accounts/count to get a JSON response with a dict with the key 'user_count'. Branch (git checkout number-supporters und git checkout -b NAME ) from number-supporters to implement the UI part.

DON'T MERGE before checking load on server (@feeds Can we create a high number of users now?)

2020-03-28 13:32 UTC, feeds commented
@Baschdl I created a test case for the url and also added a 'many-users-fixture' with about 7000 users.
You can user this to test the load on the server

2020-03-29 09:34 UTC, josauder submitted a review, later dismissed

2020-03-29 09:34 UTC, josauder commented on backend/apps/accounts/generate_users.py
>  def populate_db(request):
We should not push this as it is. Both here and in the `urls.py` route, we should use something like:

```if settings.DEBUG:
       def populate_db(...)```

2020-03-29 14:43 UTC, feeds commented
@josauder I included you change requests

2020-03-29 16:54 UTC, kevihiiin requested changes
Looks good and works on my machine

2020-03-29 16:54 UTC, kevihiiin commented on backend/apps/accounts/views.py
> +class UserCountView(APIView):
Maybe also protection for the usercount?
Not sure how usefull the normal staff_required one is for REST calls, but maybe [tokens](https://simpleisbetterthancomplex.com/tutorial/2018/11/22/how-to-implement-token-authentication-using-django-rest-framework.html)?

2020-03-29 17:06 UTC, kevihiiin approved these changes

2020-03-29 17:07 UTC, merged