Fix missing static files
Baschdl/match4healthcare pull request #277
Opened 2020-03-29 01:03 UTC by kevihiiin

- Create setup.sh for easier deployment
- Issue was whitenoise not reloading static files once it started 
 => restart container
- Modified Travis scripts

2020-03-29 09:53 UTC, josauder reviewed
LGTM, but perhaps @Baschdl should review this as he is more familiar with the deployment process

2020-03-29 18:19 UTC, Baschdl requested changes

2020-03-29 18:19 UTC, Baschdl commented on .travis.yml
> + - ./setup.sh
Having two similar scripts is suboptimal

2020-03-29 18:19 UTC, Baschdl commented on README.md
> +### Production
Merge with "Production" at the bottom of this file

2020-03-29 18:19 UTC, Baschdl commented on backend/match4healthcare/urls.py
> -    path('android-icon-144x144.png', RedirectView.as_view(url=staticfiles_storage.url('img/favicon/android-icon-144x144.png'))),
This was (is?) necessary because a browser calls `https://match4healthcare.de/android-icon-144x144.png` but the file is located at `https://match4healthcare.de/static/img/android-icon-144x144.sdf35fd.png`. Did you change something in the setup?

2020-03-29 18:19 UTC, Baschdl commented on scripts/check_website_availability.sh
> +	# Check if log file exists
Comment vom stackoverflow?

2020-03-29 18:19 UTC, Baschdl commented on setup.sh
> +# Collect static BEFORE the container starts
Misleading because `backend` is already running

2020-03-29 19:24 UTC, kevihiiin commented on backend/match4healthcare/urls.py
> -    path('android-icon-144x144.png', RedirectView.as_view(url=staticfiles_storage.url('img/favicon/android-icon-144x144.png'))),
We supply the favicon in the head of our document
`<link rel="icon" type="image/png" sizes="192x192" href="{% static 'img/favicon/android-icon-192x192.png' %}">
`
which points to the correct static location (fixed by Andreas a few days back)

2020-03-29 19:28 UTC, kevihiiin commented on scripts/check_website_availability.sh
> +	# Check if log file exists
Thanks for the reminder, yes got the curl status code part from [here](https://superuser.com/a/442395), will add as attribution. Otherwise this downloads a page and checks if the status code equals 200

2020-03-29 19:29 UTC, kevihiiin commented on .travis.yml
> + - ./setup.sh
Will be merged into ./deploy.sh

2020-03-29 19:30 UTC, kevihiiin commented on setup.sh
> +# Collect static BEFORE the container starts
Yep, I think the restart comment following that is enough

2020-03-30 01:39 UTC, Baschdl approved these changes

2020-03-30 02:11 UTC, merged