Migrate first in case we have outstanding migrations
Baschdl/match4healthcare pull request #340
Opened 2020-04-01 20:50 UTC by Baschdl

Current deploy script fails if we have outstanding migrations

2020-04-06 07:59 UTC, Baschdl commented
@kevihiiin How to do this?

2020-04-12 23:49 UTC, maltezacharias requested changes

2020-04-12 23:49 UTC, maltezacharias commented on deploy.sh
> +docker exec backend python3 manage.py migrate
- Why don't we override CMD for this? If the previous step fails/exits, this will fail, depending on the speed or not?

2020-04-12 23:49 UTC, maltezacharias commented on deploy.sh
> +docker exec backend python3 manage.py migrate
Why do we use django-admin for the next couple of lines, but not this one?

2020-04-14 20:40 UTC, Baschdl commented on deploy.sh
> +docker exec backend python3 manage.py migrate
An exited container is exited no matter what. You're right this would also fail but if we can't even build the container, I see no sense in trying to run the migrations

2020-04-14 20:42 UTC, Baschdl commented on deploy.sh
> +docker exec backend python3 manage.py migrate
Because our README also uses manage.py :D

2020-04-15 22:28 UTC, maltezacharias approved these changes

2020-04-15 22:34 UTC, merged