Language switching
Baschdl/match4healthcare pull request #367
Opened 2020-04-03 19:17 UTC by josauder

2020-04-03 19:20 UTC, Baschdl commented
I needed like two years to understand that symbol on Wikipedia. How about something like 🌍?

2020-04-03 19:24 UTC, Baschdl requested changes
"Deutsch" and "Englisch" redirect to `/en/` in an English browser

2020-04-03 19:30 UTC, Baschdl submitted a review, later dismissed
Drop-down only works for 60% of all clicks in Firefox

2020-04-03 22:30 UTC, Baschdl approved these changes
Works like a charm

2020-04-03 22:33 UTC, Baschdl commented on backend/apps/accounts/templates/student_edit.html
> +                Wir haben <a href="/de/legal-questions">rechtliche Hinweise und Tipps</a> zu deinem Einsatz nach bestem Wissen und Gewissen zusammen gefasst. Darunter sind hinweise für Arbeitszeitenr
Why would you hardcode it here? Maybe someone prefers English in general but also understands German

2020-04-03 22:33 UTC, Baschdl commented on backend/apps/accounts/views.py
> +    return HttpResponseRedirect("/accounts/password_reset/done")
This is keeping the language setting?

2020-04-03 23:00 UTC, closed without merging

2020-04-04 10:37 UTC, Baschdl commented
@maltezacharias @feeds @josauder Wow, I blick' gar nicht mehr was hier abgeht. Wurden meine concerns irgendwo behandelt?

2020-04-08 17:39 UTC, maltezacharias commented
@Baschdl wir haben gemerkt, dass die URLs mit /de/... vorne dran komplett unnötig kompliziert waren, wir haben uns für die viel einfachere Lösung entschieden, dass über nen Cookie zu switchen und mussten dann nix mehr ändern PR #369, deswegen haben wir hier abgebrochen