394 Log errors to Slack / Logging improvement
Baschdl/match4healthcare pull request #420
Opened 2020-04-12 23:33 UTC by maltezacharias

# Changes

- Adds a new Custom Log Handler to send Errors to Slack
- Adds a new Environment Variable to configure Slack Webhook URL
- Overhauls the complete logging configuration
- Adds JSON structured logging format
- Adds applicationwide logging configuration (using logging.getLogger(__name__) in all project folders under apps/
- Hides django.server logs (only produced by runserver and not necessary)
- Includes new logging example in ineedstudent/views.py
- Logging to console is reduced to one line per log entry, newlines are removed, timestamps are added
- closes #394 

JSON Logging compatible with https://github.com/gistia/json-log-viewer recommended as log viewer

## TODOs: 
- Password fields need to be excluded from logging (cave: request.POST!, cave: request.user!)
- Filesize should be monitored in the beginning
- Care must be taken not to include data with circular references
- Consider alternate JSON lib
- Performance should be monitored, increased audit logging should be added throughout the app.

## Example output:
![image](https://user-images.githubusercontent.com/9914287/79082447-61b98980-7d26-11ea-977d-d8d8e1f88f61.png)
![image](https://user-images.githubusercontent.com/9914287/79082470-8877c000-7d26-11ea-8cc7-21af0bb6a98b.png)

```json
{
   "status_code":500,
   "request":{
      "method":"POST",
      "GET":{

      },
      "POST":{
         "csrfmiddlewaretoken":"",
         "name_first":"dfgs",
         "name_last":"dfgs",
         "email":"fgsfg@srdgsfghsas.sdfad",
         "phone_number":"",
         "plz":"99999",
         "countrycode":"DE",
         "umkreis":"1",
         "availability_start":"2020-04-11",
         "initial-availability_start":"2020-04-11 21:34:27",
         "braucht_bezahlung":"2",
         "zeitliche_verfuegbarkeit":"1",
         "ausbildung_typ_medstud_abschnitt":"0",
         "ausbildung_typ_mfa_abschnitt":"0",
         "ausbildung_typ_mtla_abschnitt":"0",
         "ausbildung_typ_mta_abschnitt":"0",
         "ausbildung_typ_ota_abschnitt":"0",
         "ausbildung_typ_ata_abschnitt":"0",
         "ausbildung_typ_notfallsani_abschnitt":"0",
         "ausbildung_typ_pflege_abschnitt":"0",
         "ausbildung_typ_ergotherapie_abschnitt":"0",
         "ausbildung_typ_psycho_abschnitt":"0",
         "ausbildung_typ_zahni_abschnitt":"0",
         "ausbildung_typ_physio_abschnitt":"0",
         "ausbildung_typ_kinderbetreung_ausgebildet_abschnitt":"0",
         "sonstige_qualifikationen":"keine"
      },
      "path":"/accounts/signup_student"
   },
   "level":"error",
   "message":"[django.request]: Internal Server Error: /accounts/signup_student",
   "timestamp":"2020-04-12T21:54:39.284234",
   "user":"AnonymousUser",
   "exc_info":"Traceback (most recent call last):..... ypeError: can only concatenate str (not \"__proxy__\") to str"
}
```

2020-04-14 02:10 UTC, maltezacharias commented
Passwords are now hidden when DEBUG is False using the default Django Implementation to hide sensitive values from requests marked using the @method_decorator(sensitive_post_parameters())

(This is true for the default login forms)

2020-04-14 20:47 UTC, Baschdl requested changes
A check like in #402 would also be nice here.

Do you intend to implement the TODOs?

2020-04-14 20:51 UTC, Baschdl commented on backend/match4healthcare/logging/formatters.py
> +        result = super(OneLineExceptionFormatter, self).formatException(exc_info)
Does this output the JSON or the old format in one line?

2020-04-14 20:58 UTC, maltezacharias commented on backend/match4healthcare/logging/formatters.py
> +        result = super(OneLineExceptionFormatter, self).formatException(exc_info)
Neither :) Basically you configure the log string in the logging configuration. The only difference is, that the default formatting will add Exception Stacktraces after your  formatted log message, this one will append it to your logline and replace newlines with something else

2020-04-14 21:03 UTC, Baschdl submitted a review, later dismissed

2020-04-14 21:03 UTC, Baschdl commented on backend/requirements.txt
> +JSON-log-formatter
Please specify the used version

2020-04-15 09:58 UTC, feeds commented on backend/requirements.txt
> +JSON-log-formatter
done

2020-04-15 10:07 UTC, feeds approved these changes
This worked very nicely, maybe we should make it more transparent which messages should be logged where though.

2020-04-15 15:15 UTC, merged