new pictogram on landing page, new about text, new data privacy, new …
Baschdl/match4healthcare pull request #441
Opened 2020-04-26 14:13 UTC by andyz02

…footer text

2020-05-01 06:09 UTC, Baschdl requested changes

2020-05-01 06:09 UTC, Baschdl commented on backend/templates/dataprotection.html
> +          <li>IP-Adresse</li>
Where do we save the IP?

2020-05-01 06:09 UTC, Baschdl commented on backend/templates/dataprotection.html
> +  <div style="height:40px"></div>
Can we just change the data protection rules without notifying the users?

2020-05-01 06:09 UTC, Baschdl commented on backend/templates/home.html
> +			<p style="text-align:center;">match4healthcare vernetzt Helfende und Hilfesuchende aus dem Gesundheitswesen anhand von Kriterien wie Qualifikation, Verfügbarkeit und Wunschtätigkeit auf der einen
Translation missing

2020-05-07 22:00 UTC, andreaskind commented on backend/templates/dataprotection.html
> +          <li>IP-Adresse</li>
The whole document is a product of a conversation between our legal counsellor and @maltezacharias . I guess we're not saving but collect it in the first place, which should be declared as well?

2020-05-07 22:01 UTC, andreaskind commented on backend/templates/dataprotection.html
> +  <div style="height:40px"></div>
Yes, last time i asked our legal advice, we can, but I'll double check

2020-05-11 21:37 UTC, Baschdl submitted a review, later dismissed
We also need a translation of the pretty pictogram

2020-05-14 13:50 UTC, andreaskind commented
@Baschdl pictogramm of the frontpage has been translated and added to the static/img folder

2020-05-14 21:07 UTC, bjrne commented
The image translation logic works. Please check the english version again @andreaskind, I cropped and downsized it to be appropriate for a website. It still differs in fonts and colors from the german version though, but that wouldn't be an issue for me. Otherwise this should be good to go.

2020-05-17 20:31 UTC, bjrne commented on backend/templates/base.html
>                      target="_blank">#WirVsVirus Hackathons</a>. <a
Missing translation, will fix.

2020-05-18 14:29 UTC, kevihiiin commented
> The image translation logic works. Please check the english version again @andreaskind, I cropped and downsized it to be appropriate for a website. It still differs in fonts and colors from the german version though, but that wouldn't be an issue for me. Otherwise this should be good to go.

The language settings for the image work nicely, but the translation for the rest of the site broke completely. The cookie is set correctly, will look into that after I reviewed all the changes

2020-05-18 14:58 UTC, kevihiiin commented on backend/templates/terms-of-use.html
> +<p>Zur Gewährleistung der Datenminimierung gibt match4healthcare keine Namen und Kontaktdaten von Helfenden an die Hilfesuchenden weiter. Die unmittelbare Kontaktaufnahme erfolgt stets durch den Helf
```suggestion
<p>Zur Gewährleistung der Datenminimierung gibt match4healthcare keine Namen und Kontaktdaten von Helfenden an die Hilfesuchenden weiter. Die unmittelbare Kontaktaufnahme erfolgt stets durch den Helfenden. Die Darstellung der Helfenden findet auf der Helferkarte lediglich in Gestalt der Anzahl der Helfenden in einem bestimmten Postleitzahlenbereich statt. In den Hilfesuchenden zur Verfügung gestellten Listen über potentielle Helfende werden darüber hinaus Qualifikationen, Verfügbarkeit sowie ein eventueller Wunsch nach Unterkunft und Bezahlung der Hilfe bietenden mitgeteilt.</p>
```
The last sentence was a bit hard to understand, maybe this makes it clearer

2020-05-18 15:01 UTC, kevihiiin commented on backend/templates/impressum.html
> +                <strong>match4healthcare e.V. (in Gründung)</strong><br><br>
Are we still "in Gründung"?

2020-05-18 15:09 UTC, kevihiiin approved these changes

2020-05-18 19:24 UTC, bjrne commented on backend/templates/terms-of-use.html
> +<p>Zur Gewährleistung der Datenminimierung gibt match4healthcare keine Namen und Kontaktdaten von Helfenden an die Hilfesuchenden weiter. Die unmittelbare Kontaktaufnahme erfolgt stets durch den Helf
Hm, finds dann fast verständlicher wenns "In den *den* Hilfesuchenden" zur Verfügung [...]" ist :see_no_evil: Ist mir persönlich aber egal.

2020-05-18 19:25 UTC, bjrne commented on backend/templates/impressum.html
> +                <strong>match4healthcare e.V. (in Gründung)</strong><br><br>
Not sure, further down it also just says "match4healthcare e.V.". @andreaskind?

2020-05-18 21:20 UTC, Baschdl commented on backend/templates/dataprotection.html
> +          <li>IP-Adresse</li>
@maltezacharias has to respond to this regarding the nginx but we don't look at it in the python code

2020-05-18 21:23 UTC, Baschdl commented on backend/templates/terms-of-use.html
> +<p>Zur Gewährleistung der Datenminimierung gibt match4healthcare keine Namen und Kontaktdaten von Helfenden an die Hilfesuchenden weiter. Die unmittelbare Kontaktaufnahme erfolgt stets durch den Helf
Ist "Zur Gewährleistung der Datenminimierung gibt match4healthcare keine Namen und Kontaktdaten von Helfenden an die Hilfesuchenden weiter." wirklich korrekt, wenn ein Helfender direkt einen Hilfesuchenden anschreibt?

2020-05-18 22:34 UTC, kevihiiin commented on backend/templates/terms-of-use.html
> +<p>Zur Gewährleistung der Datenminimierung gibt match4healthcare keine Namen und Kontaktdaten von Helfenden an die Hilfesuchenden weiter. Die unmittelbare Kontaktaufnahme erfolgt stets durch den Helf
> Hm, finds dann fast verständlicher wenns "In den _den_ Hilfesuchenden" zur Verfügung [...]" ist 🙈 Ist mir persönlich aber egal.

Gerne auch das:) Ich bin nur bin nur über den Satz "zu eine Unterkunft wünscht" gestolpert und hab ihn nicht ganz verstanden. Ich glaube "zu eine[r] Unterkunft wünscht" passt auch.

2020-05-19 12:25 UTC, bjrne commented on backend/templates/terms-of-use.html
> +<p>Zur Gewährleistung der Datenminimierung gibt match4healthcare keine Namen und Kontaktdaten von Helfenden an die Hilfesuchenden weiter. Die unmittelbare Kontaktaufnahme erfolgt stets durch den Helf
```suggestion
<p>Zur Gewährleistung der Datenminimierung gibt match4healthcare keine Namen und Kontaktdaten von Helfenden an die Hilfesuchenden weiter. Die unmittelbare Kontaktaufnahme erfolgt stets durch den Helfenden. Die Darstellung der Helfenden findet auf der Helferkarte lediglich in Gestalt der Anzahl der Helfenden in einem bestimmten Postleitzahlenbereich statt. In den den Hilfesuchenden zur Verfügung gestellten Listen über potentielle Helfende werden darüber hinaus Qualifikationen, Verfügbarkeit sowie ein eventueller Wunsch nach Unterkunft und Bezahlung der Hilfebietenden mitgeteilt.</p>
```

2020-05-19 12:37 UTC, merged