Pep8
Baschdl/match4healthcare pull request #450
Opened 2020-05-02 12:21 UTC by bjrne

This adds pre commit checks for various issues and formats code to `black`-standards.

2020-05-02 13:01 UTC, Baschdl requested changes
Overall nice formatting

2020-05-02 13:01 UTC, Baschdl commented on backend/apps/accounts/email_utils.py
> -    recipients_personalisations = [
This was maybe a deliberate formating

2020-05-02 13:01 UTC, Baschdl commented on backend/apps/accounts/email_utils.py
> -        "content": [{"type": "text/html",
I find this one clearer

2020-05-02 13:01 UTC, Baschdl commented on backend/apps/accounts/generate_users.py
> -big_city_plzs = ['01067', '01069', '01097', '01099', '01109', '01127', '01129', '01139', '01157', '01159', '01169',
This one. Can you add exceptions for the formatting?

2020-05-02 13:01 UTC, Baschdl commented on backend/apps/accounts/templates/change_activation_ask.html
> -
It changed HTMLs but very conservative

2020-05-02 13:01 UTC, Baschdl commented on backend/apps/accounts/views.py
> +from apps.ineedstudent.forms import (
Interesting

2020-05-02 20:16 UTC, bjrne commented on backend/apps/accounts/templates/change_activation_ask.html
> -
It only changes file endings and whitespaces so far, an html formatter will be added in a later PR

2020-05-02 20:17 UTC, bjrne commented on backend/apps/accounts/generate_users.py
> -big_city_plzs = ['01067', '01069', '01097', '01099', '01109', '01127', '01129', '01139', '01157', '01159', '01169',
No. I will manually ignore this file.

2020-05-02 20:18 UTC, bjrne commented on backend/apps/accounts/email_utils.py
> -    recipients_personalisations = [
black deliberately ignores these for an overall consistent and easily formatted codebase

2020-05-02 20:25 UTC, kevihiiin commented on backend/apps/accounts/utils.py
> -def generate_random_username(length=16, chars=ascii_lowercase+digits, split=4, delimiter='-'):
Can we set the threshold for method signatures higher?

2020-05-02 20:53 UTC, kevihiiin commented on scripts/check_website_availability.sh
> +		if [[  $(curl -s -o /dev/null -w "%{http_code}\n" $URL) -eq 200 ]]; then
Are there specific checks for bash scripts `.sh` files?
To ensure that single quotes are not replaced with double quotes

2020-05-02 20:54 UTC, bjrne commented on scripts/check_website_availability.sh
> +		if [[  $(curl -s -o /dev/null -w "%{http_code}\n" $URL) -eq 200 ]]; then
We currently don't run any formatting on .sh files apart from: 
- file endings
- trailing whitespaces
- line endings

2020-05-02 21:06 UTC, kevihiiin commented on .pre-commit-config.yaml
> +        exclude: ^backend/static/
Can we also exclude `backend/backups` `backend/run` ? 
They are not commited into the repository and therefore do not need to be formatted / checked

2020-05-02 21:09 UTC, kevihiiin commented on backend/apps/accounts/utils.py
> -def generate_random_username(length=16, chars=ascii_lowercase+digits, split=4, delimiter='-'):
Although the formatting seems quite strict sometimes, I can see the benefits of breaking a line into more separate ones (better [diffs](https://github.com/psf/black))

2020-05-02 21:19 UTC, kevihiiin commented on .pre-commit-config.yaml
> +        exclude: ^backend/apps/[a-z]*/migrations/[0-9A-z]*.py
Add additional `language_version` and set to 3.6 (is the minimum required version for Django 3.0.5)

Further material:
https://black.readthedocs.io/en/stable/version_control_integration.html
or `target_version` in the cli version https://pypi.org/project/black/

```suggestion
        language_version: python3.6
        exclude: ^backend/apps/[a-z]*/migrations/[0-9A-z]*.py
```

2020-05-02 21:20 UTC, kevihiiin approved these changes

2020-05-03 11:18 UTC, bjrne commented on .pre-commit-config.yaml
> +        exclude: ^backend/static/
In theory, this should not be necessary as the git commit hook only passes modified files to the handler, but if it should ever be necessary to run `pre-commit run --all-files` again, we will be on the safe side now :)

2020-05-03 11:57 UTC, bjrne commented on backend/apps/accounts/utils.py
> -def generate_random_username(length=16, chars=ascii_lowercase+digits, split=4, delimiter='-'):
I changed the max line length too 100, which solves most of these cases and is still readable. If signatures are longer, maybe they really do need to get some attention ;)

2020-05-03 13:48 UTC, Baschdl requested changes
Could you please also mention `pre-commit run` in the README?

2020-05-03 14:26 UTC, Baschdl approved these changes

2020-05-03 14:43 UTC, merged

2020-05-03 17:23 UTC, bjrne commented on .pre-commit-config.yaml
> +        exclude: ^backend/apps/[a-z]*/migrations/[0-9A-z]*.py
Actually, this does more harm than good and causes bug #482. Is there an important reason to add this? Black works fine without, and this would not be the place to add this. In order to be a version check, it would need to be its own hook. @kevihiiin