Initial version of a statistics page
Baschdl/match4healthcare pull request #453
Opened 2020-05-02 15:45 UTC by feeds

2020-05-02 19:43 UTC, Baschdl commented
We need a better user permission for this. @maltezacharias is on it

2020-05-03 00:20 UTC, feeds commented
Well, we should open another issue for this, right?

I can easily add another group of 'statsviewers', what is @maltezacharias onto? 😅

2020-05-03 14:55 UTC, Baschdl commented
Yes, he opened #466. Shouldn't prevent this PR from merging

2020-05-03 16:00 UTC, Baschdl requested changes
Did you leave out "Deactivated Institutions" on purpose?

2020-05-03 16:00 UTC, Baschdl commented on backend/apps/accounts/db_stats.py
> +            Student.objects.filter(is_activated=True).count(),
Shouldn't that be `False`?
```suggestion
            Student.objects.filter(is_activated=False).count(),
```

2020-05-03 16:00 UTC, Baschdl commented on backend/apps/accounts/db_stats.py
> +        return (_("Kontaktanfragen an Institutionen"), EmailToHospital.objects.filter().count())
```suggestion
        return (_("Kontaktanfragen an Institutionen"), EmailToHospital.objects.count())
```

2020-05-03 16:00 UTC, Baschdl commented on backend/apps/accounts/db_stats.py
> +    def students_contacted_by_hospital(self):
```suggestion
    def emails_to_students(self):
```
The method sounds like the number of unique students which where contacted

2020-05-03 16:00 UTC, Baschdl commented on backend/apps/accounts/db_stats.py
> +    def hospitals_contacted_by_students(self):
```suggestion
    def emails_to_hospitals(self):
```

2020-05-04 08:36 UTC, feeds commented
I did not know they could deactivate themselves. I can add it if required.

2020-05-05 15:13 UTC, Baschdl commented
> I did not know they could deactivate themselves. I can add it if required.

Now I'm not sure either. Isn’t that part of the basic user functionality? If it's not, why can’t they deactivate themselves if they found someone for now but need more help later?

Can’t test it locally right now.

2020-05-12 10:32 UTC, Baschdl approved these changes
Otherwise it's fine

2020-05-12 10:32 UTC, Baschdl commented on backend/apps/accounts/db_stats.py
> +                results.append(r)
```suggestion
            results.extend(m(self))
```

2020-05-12 10:58 UTC, feeds commented
thank youuu :)

2020-05-12 11:46 UTC, merged

2020-05-13 11:36 UTC, bjrne reviewed
Nooooooooo :D

2020-05-13 11:36 UTC, bjrne commented on backend/apps/accounts/db_stats.py
> +    # TODO: last X days? # noqa: T003
This is not the idea @Baschdl :laughing: 
Either its an idea that isn't worth pursuing, or it is a TODO and should get its own issue for keeping track of it :D

2020-05-13 11:36 UTC, bjrne commented on backend/apps/accounts/db_stats.py
> +    # https://github.com/match4everyone/match4healthcare/issues/492
Same here, the issue is supposed to be about the TODO itself. In this way, nobody will ever check this again. If they were linked on github, one could see more easily whether the dependency issue is closed.

2020-05-13 12:48 UTC, Baschdl commented on backend/apps/accounts/db_stats.py
> +    # TODO: last X days? # noqa: T003
That's a PO issue where we just have to wait for input from the rest. Not sure if opening an issue for all TODOs is a good idea. I fear that the issues will get completely messy

2020-05-13 12:50 UTC, Baschdl commented on backend/apps/accounts/db_stats.py
> +    # https://github.com/match4everyone/match4healthcare/issues/492
We can reference this as `dependent` in 492 but I wouldn't open a separate issue