Reorganize system checks
Baschdl/match4healthcare pull request #477
Opened 2020-05-03 13:36 UTC by feeds

2020-05-03 15:01 UTC, bjrne commented on backend/match4healthcare/settings/production.py
> +if not IS_FORK:
@feeds please double check whether I merged this file correctly :)

2020-05-03 15:02 UTC, bjrne commented
I took the liberty to resolve the merge conflicts that appeared due to the new styling in staging. Please have a look again to make sure I merged correctly :)

2020-05-04 08:38 UTC, feeds commented
> I took the liberty to resolve the merge conflicts that appeared due to the new styling in staging. Please have a look again to make sure I merged correctly :)

Yees, if the tests dont break that formatting is fine with me :)

2020-05-05 08:27 UTC, feeds commented on backend/match4healthcare/settings/production.py
> +if not IS_FORK:
yes its correct!

2020-05-05 08:27 UTC, feeds commented
@bjrne would you approve?

2020-05-05 12:08 UTC, bjrne commented
I think @kevihiiin would be much mure suited for this, I don't even know how to test this :sweat_smile:

2020-05-05 21:25 UTC, kevihiiin commented
I will approve test it

2020-05-05 23:18 UTC, kevihiiin commented on backend/match4healthcare/settings/common.py
> +class ENVS:
I know this is sounds academic and nit picky :D but can we use enums here? (and rename the class to e. g. `Stage` - with only the final constant in all caps)
Would looky very similar to the class
https://docs.python.org/3.6/library/enum.html

2020-05-05 23:41 UTC, kevihiiin commented on backend/match4healthcare/settings/common.py
> +    IS_FORK = True
I think we can shorten this logic into the following statement:
```suggestion
IS_FORK = False

if IS_TRAVIS and os.environ["TRAVIS_PULL_REQUEST_SLUG"] is ["match4everyone/match4healthcare"]:
    IS_FORK = True
```

2020-05-05 23:52 UTC, kevihiiin commented on backend/match4healthcare/settings/production.py
>      EMAIL_FILE_PATH = os.path.join(RUN_DIR, "sent_emails")
Is it possible to remove this part of altering the settings (because this might be confusing to understand that this only affects travis checks) and move the warning into the decorator `register_checks`?

If we really need to have different settings for testing I suggest that we create a third settings file similar to production called `testing.py`. Might not be a bad idea :D

2020-05-06 00:11 UTC, kevihiiin requested changes
Looks very clever and nice :+1: 
I have tested it on my fork with travis and everything works as expected, but have not tried it manually / locally, will do after the final changes :)

2020-05-06 19:36 UTC, feeds commented on backend/match4healthcare/settings/common.py
> +class ENVS:
Enum is nice, I agree.

With regards to caps, we would need define the enum in another file if we used camel case. 
Django-internal only all-caps setting variables are made available to other files via settings.VARIABLE (see here)[https://docs.djangoproject.com/en/dev/topics/settings/#creating-your-own-settings]. So we wouldn't be able to access the Enum in the 'checks.py'

But since it not really a setting anyways it should probably go elsewhere. Any suggestions?

2020-05-07 23:23 UTC, kevihiiin commented on backend/match4healthcare/settings/common.py
> +class ENVS:
Good to know, that Django settings requires all-caps variable names when it is being imported :)

How about creating a file similar to this `backend/match4healthcare/constants/enum.py`?
(or another name for 'constants')

2020-05-11 13:53 UTC, feeds commented on backend/match4healthcare/settings/common.py
> +class ENVS:
Done :)

2020-05-11 14:04 UTC, feeds commented on backend/match4healthcare/settings/production.py
>      EMAIL_FILE_PATH = os.path.join(RUN_DIR, "sent_emails")
I would wait to create a new file until we really need different settings for testing apart from that one case.

I added a check for fork instead of only moving the logging to checks. I think this is more verbose.

2020-05-11 18:23 UTC, kevihiiin approved these changes
Looks perfect, thanks for the changes

2020-05-11 19:32 UTC, merged