Add visualization of statistics with history
Baschdl/match4healthcare pull request #503
Opened 2020-05-12 11:07 UTC by Baschdl

![image](https://user-images.githubusercontent.com/3034832/81677671-6f5f4d80-9451-11ea-825a-d815d0904639.png)

2020-05-12 14:18 UTC, feeds requested changes
I like the graphs - I just changed the code structure a little to make it more maintainable.
Also I added another date cause somehow the lte does not work as one would expect (does not inlclude todays changed to the db).

I changed a lot, so my change request is to review my changes yourself @Baschdl

2020-05-12 18:09 UTC, bjrne commented on backend/requirements.txt
> +jinja2==2.11.2
Is `jinja2` still necessary? It is not used in the code. I think we shouldn't list transitive dependencies in the requirements.

2020-05-12 22:08 UTC, Baschdl commented on backend/requirements.txt
> +jinja2==2.11.2
We have to do this until https://github.com/mpld3/mpld3/pull/457 is merged

2020-05-18 21:44 UTC, Baschdl commented on backend/apps/accounts/views_staff.py
> +    for name, history in graphs:
I would refactor this to a separate method, not sure if it fits more to the `views.py` because it builds part of the html or to the `db_stats.py` because it includes some specific logic

2020-05-18 21:44 UTC, Baschdl commented on backend/apps/accounts/db_stats.py
> +    dated_count = RegisterList()
Did you first plan to create a separate decorator?

2020-05-18 21:44 UTC, Baschdl commented on backend/apps/accounts/db_stats.py
> +        return lambda func: self.register_named(name, func)
Do you intend to use `register_named`somewhere else? If not, mark it as "private", change the order of `register_named` and `register` and/or write a nice comment explaining how to use the decorator

2020-05-18 21:44 UTC, Baschdl commented on backend/apps/accounts/db_stats.py
> +        return range(self.length_history_days, 0 - 2, -1)
The magic `-2` also needs some documentation

2020-05-18 21:44 UTC, Baschdl commented on backend/apps/accounts/db_stats.py
> +    def generate_cum_graph(self, count_func):
Not sure what `generate_`**cum**`_graph` should mean

2020-05-19 12:01 UTC, bjrne commented on backend/apps/accounts/db_stats.py
> +    def generate_cum_graph(self, count_func):
in numpy it usually stands for *cumulative*. Maybe for clarifying that the graph lists absolute numbers and not relative registration counts?

2020-05-30 19:11 UTC, Baschdl commented
@feeds 😬

2020-07-01 17:14 UTC, Baschdl commented
@feeds Can we solve the open points and then merge it into m4h and m4e?

2020-07-01 17:43 UTC, feeds commented on backend/apps/accounts/db_stats.py
> +    def generate_cum_graph(self, count_func):
its not a daily view, but displays the sum of all X until a specific day

2020-07-01 17:46 UTC, feeds approved these changes

2020-07-01 17:55 UTC, merged

2020-07-01 18:03 UTC, bjrne commented
Not sure this is what @Baschdl meant with _solve the open points_ :grin:

2020-07-07 11:33 UTC, Baschdl commented
@bjrne @feeds No, it wasn't. Reviews are kind of useless like this