Move models to seperate files
Baschdl/match4healthcare pull request #509
Opened 2020-05-14 17:56 UTC by feeds

2020-05-15 07:55 UTC, feeds commented
The newsletter model contains a bug that is solved in #510

2020-05-16 18:19 UTC, bjrne reviewed
Apart from the small comments, I really like it!

2020-05-16 18:19 UTC, bjrne commented on backend/match4healthcare/utils/imports.py
> +import six
Do we really need python2 compatibility? I would lobby against it and use python3 syntax.

2020-05-16 18:19 UTC, bjrne commented on backend/match4healthcare/utils/imports.py
> +        # this causes a Runtime error with model conflicts
Is the occurence of this runtime error tested or just copied from the source? Maybe it is not an issue with python3 or stuff.

2020-05-16 18:19 UTC, bjrne commented on backend/apps/ineedstudent/views/__init__.py
> +import_submodules(globals(), __name__, __path__)
Let's test this with more people of our team whether this works with IDE linting or whether we need special configuration for this to work, which should then maybe be included in the repository.

2020-05-18 14:33 UTC, feeds commented on backend/apps/ineedstudent/views/__init__.py
> +import_submodules(globals(), __name__, __path__)
Yes, maybe we can create a new issue for tihs? I think the understandability of the code with this refactoring improves so much that the code linting is not the bigger issue here.
At least I think it works with black, it kept correcting my commits for import style...

2020-05-18 21:49 UTC, Baschdl requested changes

2020-05-18 21:49 UTC, Baschdl commented on backend/apps/accounts/tables.py
> +from .modelss import Newsletter, NewsletterState
🙈

2020-05-22 23:23 UTC, kevihiiin commented on backend/apps/ineedstudent/views/__init__.py
> +import_submodules(globals(), __name__, __path__)
My IDE also reports back that the modules (models) cannot be found. It also breaks the `manage.py createfakeusers` command for me.

Is there a certain order in which the submodules are loaded? If it is alphabetically the order might change when we add new one

2020-05-22 23:48 UTC, kevihiiin commented on backend/apps/ineedstudent/views/__init__.py
> +import_submodules(globals(), __name__, __path__)
Another (manual and not so elegant) alternative would be to explicitly list all the packages like so:
`from .hospital import *` 
or even better only import modules / variables that are actually used

This way the IDEs should be able to find the modules as it is not dynamically loaded and the order of imports is fixed (if that is important)

Suggested by the Django documentation:
https://docs.djangoproject.com/en/3.0/topics/db/models/#organizing-models-in-a-package

2020-05-23 20:32 UTC, feeds commented on backend/apps/accounts/tables.py
> +from .modelss import Newsletter, NewsletterState
das ist das letzte was geänder wird bevor es fertig ist <3

2020-05-27 09:33 UTC, bjrne commented on backend/apps/accounts/models/__init__.py
> +if STATIC_HACK:
LOL :rofl:

2020-06-30 21:23 UTC, maltezacharias commented
@feeds How should we handle this atm? Should we
- close the PR?
- review & merge?
- do something else?

What state is this in?

2020-06-30 21:46 UTC, feeds commented
it seemed like a too risky change to apply this to the repo. Wer just users it in m4e.

so i think this can be closed

2020-06-30 22:12 UTC, maltezacharias commented
Major changes are for now not planned to be implemented in m4h. 
A more complete redesign using these concepts has been applied to m4e

2020-06-30 22:12 UTC, closed without merging