Add sample gateway error page
Baschdl/match4healthcare pull request #538
Opened 2020-06-19 22:31 UTC by maltezacharias

Adds a couple of files to the repository that show how to setup an error page for when the app server is not running on an nginx gateway. Also includes stripped down bootstrap layout and a sticky footer without JS which could be interesting for m4e

2020-06-19 22:32 UTC, maltezacharias commented
@bjrne Ich krieg da nen Fehler weil ich ein File >500kb versuche zu comitten. Ich glaub die Grenze ist zu niedrig. Ich hab das Bild so klein gemacht wie es geht, aber wenn man auch 4K Displays bedienen will geht einfach nicht weniger

2020-06-19 23:24 UTC, bjrne commented
Ich hab da keine Grenze festgelegt, das ist ein sensible default. Ich finde es ist lange an der Zeit, lfs für sowas zu benutzen. Bilder gehören einfach nicht ins git, es ist ja auch mega nervig wenn man ein repo frisch (grade unterwegs) und er erstmal 20MB an Dateien aus der History runterlädt, die man garnicht mehr braucht.

Also: lets setup lfs :tada:, kann das auch gern machen :)

2020-06-20 00:14 UTC, maltezacharias commented
Ich musste LFS jetzt erstmal googlen, für ne Handvoll Bilder bin ich dagegen. Und 20MB oder selbst 200MB sind halt auch nicht wirklich viel.. Irgendwann wird Deutschland sicher auch noch ein funktionierendes Mobilfunknetz bekommen..

2020-06-20 11:28 UTC, bjrne commented
Wenn man das noch nie gesehen hat, wirkt es wie overkill. In der Praxis merkst du aber den Unterschied nur durch den schnelleren checkout und musst manuell garnichts machen. Es macht technisch halt keinen Sinn, Bilder zeilenweise ins .git zu speichern. Der Speicherplatz akkumuliert sich ja im git durch die history, die du mit auscheckst.

2020-06-20 12:48 UTC, bjrne commented
Durch  das sinnfreie 1GB pull-bandwith limit von github hat sich lfs vllt erledigt. Leider dauert der checkout schon jetzt einige Zeit, weil das runterladen von binary files über das git interface nicht besonders optimiert ist.

2020-06-25 22:58 UTC, maltezacharias commented
Ahh perfekt, ich hatte sowas gelesen aber keine aktuelle Doku zu den Terms & Conditions gefunden. Klares Kontra LFS in dem Fall. Mich hat auch gestört, dass es dadurch schwieriger wird einfach einen lokalen Git-Server zu haben. Gibt's inhaltlich zum PR Fragen oder können wir mergen?

2020-07-01 08:09 UTC, josauder commented on tools/nginx-sample-site
> +maltezacharias@match4healthcare:~$ cat /etc/nginx/sites-available/match4healthcare
Is this intended to be here?

2020-07-01 08:10 UTC, josauder commented on tools/nginx-sample-site
> +maltezacharias@match4healthcare:~$ cat /etc/nginx/sites-available/match4healthcare
I do not have enough nginx expertise to properly review this PR, maybe @kevihiiin or @Baschdl are better suited

2020-07-01 12:05 UTC, kevihiiin requested changes
LGTM
I did not test the nginx configuration but I couldn't spot any errors.
Can you add a few lines to the readme about the "tools" folder?

2020-07-01 12:05 UTC, kevihiiin commented on tools/nginx-sample-site
> +maltezacharias@match4healthcare:~$ cat /etc/nginx/sites-available/match4healthcare
No I think it was accidentally copied :) The nginx server blocks start after that

```suggestion
```

2020-07-01 17:19 UTC, maltezacharias commented on tools/nginx-sample-site
> +maltezacharias@match4healthcare:~$ cat /etc/nginx/sites-available/match4healthcare
It was there to indicate where that file would normally sit. Will move to README

2020-07-01 17:38 UTC, maltezacharias commented
@kevihiiin integrated your changes, as for testing, this is a sample file not meant to be runnable without some further tinkering. It was pulled from the prod system though, so we've been testing it for a while

2020-07-01 17:48 UTC, kevihiiin approved these changes

2020-07-01 23:22 UTC, merged